---
title: "HW2: NBA2017 Player Data Dictionary"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Description
The provided data is a summary of the NBA's player data for the 2017 year including the following:
- Player: first and last names of player
- Team: 3-letter team abbreviation
- Position: Player's Position
- Experience: years of experience in NBA (a value of R means rookie)
- Salary: player salary in dollars
- Rank: Rank of plauer in his team
- Age: Age of Player at the start of February 1st of that season.
- GP: Games played during the regular season
- GS: Games Started
- MIN: Minuted Played during regular season
- FGM: Field Goals Made
- FGA: Field Goal Attempts
- Points3: 3-Point Field Goals
- Points3_atts: 3
- Point field Goal Attempts
- Points2: 2-Point Field Goals
- Points2_atts: 2-Point field Goal Attempts
- FTM: free throws made
- FTA: free throws attempt
- ORB: offensive rebound
- DRB: defensive rebound
- TRB: total rebound
- AST: assists
- STL: steals
- BLK: blocks
- TO: turnovers


## Main Source: www.basketball-reference.com
##### Sample Link: https://www.basketball-reference.com/teams/GSW/2017.html






